Document: shortener
Title: Debian shortener Manual
Author: <insert document author here>
Abstract: This manual describes what shortener is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/shortener/shortener.sgml.gz

Format: postscript
Files: /usr/share/doc/shortener/shortener.ps.gz

Format: text
Files: /usr/share/doc/shortener/shortener.text.gz

Format: HTML
Index: /usr/share/doc/shortener/html/index.html
Files: /usr/share/doc/shortener/html/*.html
